runtime: go114

instance_class: F1

# env_variables:
#   BUCKET_NAME: "example-gcs-bucket"

handlers:
- url: /css
  static_dir: public/css

- url: /js
  static_dir: public/js

- url: /(.*\.(gif|png|jpg))$
  static_files: public/images/\1
  upload: public/.*\.(gif|png|jpg)$

- url: /.*
  script: auto
  secure: always
  redirect_http_response_code: 301
