runtime: go114

instance_class: F1

# env_variables:
#   BUCKET_NAME: "example-gcs-bucket"

handlers:
- url: /css
  static_dir: public/css
  http_headers:
    Strict-Transport-Security: max-age=31536000; includeSubDomains

- url: /js
  static_dir: public/js
  http_headers:
    Strict-Transport-Security: max-age=31536000; includeSubDomains

- url: /(.*\.(gif|png|jpg))$
  static_files: public/images/\1
  upload: public/.*\.(gif|png|jpg)$
  http_headers:
    Strict-Transport-Security: max-age=31536000; includeSubDomains
    
- url: /.*
  script: auto
  secure: always
  redirect_http_response_code: 301
  http_headers:
    Strict-Transport-Security: max-age=31536000; includeSubDomains
