runtime: go126
instance_class: F1

env_variables:
  APP_ENV: "production"

# Costs saving (thanks to Go)
automatic_scaling:
  target_cpu_utilization: 0.95
  max_instances: 1
  min_instances: 0
  max_idle_instances: 1
  min_pending_latency: 3000ms
  max_concurrent_requests: 80

handlers:
  - url: /.*
    script: auto
    secure: always
