name: Deploy Application

on:
  push:
    branches:
      - main

jobs:
  deploy:
    environment: production
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "24"

      # --- BUILD SITE: RobMeijerink ---
      - name: Install & Build Rob Meijerink
        run: |
          cd sites/robmeijerink/frontend
          npm ci
          npm run build

      # --- BUILD SITE: Solvalutions ---
      # - name: Install & Build Solvalutions
      #   run: |
      #     if [ -d "sites/solvalutions/frontend" ]; then
      #       cd sites/solvalutions/frontend
      #       npm ci
      #       npm run build
      #     fi

      # --- GOOGLE CLOUD DEPLOY ---
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GOOGLE_APP_CREDENTIALS }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GOOGLE_APP_PROJECT_ID }}

      - name: Deploy to App Engine
        run: gcloud app deploy app.yaml --quiet
